version: "3.7"

services:
    impact:
        container_name: impact
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ".:/app"
