version: "3.7"

networks:
    po_webnet:
        external: true

services:
    impact:
        networks:
            - po_webnet
        volumes:
            - ".:/app"
        command:
            [
                "python",
                "main.py",
                "--productopener_base_url",
                "http://frontend/",
                "--productopener_username",
                "ecoscore-impact-estimator",
                "--productopener_password",
                "estimator",
            ]
