version: "3.7"

services:
    impact:
        container_name: impact
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        command:
            [
                "python",
                "main.py",
                "--productopener_base_url",
                "https://world.openfoodfacts.org/",
                "--productopener_host_header",
                "world.openfoodfacts.org",
            ]
