name: Test

on:
    push:
        branches: ["**"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run pytype
              run: docker-compose -f docker-compose.yml run impact pytype main.py server.py
            - name: Run tests
              run: docker-compose -f docker-compose-test.yml up
