name: Test

on:
    push:
        branches: ["**"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run pytype
              run: docker-compose -f docker-compose.yaml -f docker-compose-dev.yaml run impact pytype main.py server.py
            - name: Run tests
              run: docker-compose -f docker-compose.yaml -f docker-compose-dev.yaml run impact python server_test.py
